name: Lint & Type Check

on:
  pull_request:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Ruff & mypy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sync dependencies
        run: |
          # Install your project + dev extras so ruff/mypy are available
          uv sync --extra dev

      - name: Ruff check
        run: uvx ruff check

      - name: mypy
        run: uv run mypy ida_domain
